name: 2dfan Task Runner

on:
  push:
    branches:
      - main
  schedule:
    # - cron: '0 19 * * *'  # UTC时间19点对应北京时间3点.
    - cron: '0 22 * * *'  # UTC时间22点对应北京时间6点.
  workflow_dispatch: # 手动触发

jobs:
  run-task:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb libx11-dev xauth fonts-noto-cjk  # 安装中文字体
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Start Xvfb
      run: |
        nohup Xvfb :99 -screen 0 1280x1024x24 &

    - name: Set DISPLAY and XAUTHORITY environment variables
      run: |
        echo "DISPLAY=:99" >> $GITHUB_ENV
        echo "XAUTHORITY=/home/runner/.Xauthority" >> $GITHUB_ENV
        touch /home/runner/.Xauthority  # 创建一个空的 Xauthority 文件

    - name: Run Python script
      env:
        USER_EMAIL: ${{ secrets.USER_EMAIL }}
        USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
      run: |
        python 2dfan_DrissionPage.py

    - name: Check for failure
      if: always()  # 确保此步骤无论之前是否失败都运行
      run: |
        if [ -f "./failure_flag.txt" ]; then
          echo "Sign-in failed, sending email notification..."
          exit 1
        else
          echo "Sign-in succeeded."
        fi
        
    # - name: Upload screenshots as artifacts
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: screenshots
    #     path: |
    #       ./screenshot.png
    #       ./screenshot_detected.png
    #       ./pic1.png
    #       ./pic2.png
    #       ./pic3.png
    #       ./pic_error.png